/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_Hello.h"
/* Header for class com_Hello */

/*
 * Class:     com_Hello
 * Method:    say
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_Hello_say(JNIEnv *env, jobject obj){
    printf("Hello c");

}

